# Generated by Django 2.2.5 on 2019-09-24 19:02

from django.db import migrations, models
import django.utils.crypto
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(20,), **{}), max_length=20, unique=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
