# Generated by Django 2.2.5 on 2019-10-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_auto_20190928_1804'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Some',
        ),
    ]
