# Generated by Django 2.2.5 on 2019-11-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0005_stream_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
