# Generated by Django 2.2.5 on 2019-11-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0006_auto_20191126_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='stream_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='key',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
