# Generated by Django 2.2.5 on 2019-09-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stream',
        ),
    ]
